name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    # v0.9.0: Windows専用リリース
    # v1.0.0以降で macOS, Linux対応予定
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: pnpm test
        continue-on-error: true
      
      - name: Build application
        run: pnpm build
      
      - name: Package application (Windows)
        run: pnpm run package:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release artifacts (Windows)
        uses: actions/upload-artifact@v4
        with:
          name: windows-release
          path: |
            release/*.exe
            release/*.zip

  create-release:
    needs: release
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-release/*
          body: |
            ## ゆにぱけスキャナー v${{ github.ref_name }}

            **Windows専用リリース**

            このバージョンはWindows 10以降（64bit）専用です。
            macOS・Linux版は将来のバージョン（v1.0.0以降）で対応予定です。

            ### インストール方法
            1. `unitypackage-scanner-Setup-*.exe` をダウンロード
            2. ダウンロードしたファイルを実行してインストール

            ### 主な変更点
            自動生成されたリリースノートを参照してください。
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}