name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    # v0.9.0: Windows専用リリース
    # v1.0.0以降で macOS, Linux対応予定
    runs-on: windows-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20.x
          cache: 'pnpm'
      
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Run tests
        run: pnpm test
        continue-on-error: true
      
      - name: Build application
        run: pnpm build
      
      - name: Package application (Windows)
        run: pnpm run package:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Create release archive
        shell: pwsh
        run: |
          $version = "0.9.0"
          $zipName = "unitypackage-scanner-$version-windows.zip"

          # Create temp directory for archive contents
          New-Item -ItemType Directory -Force -Path "release-archive"

          # Copy files
          Copy-Item "release/unitypackage-scanner-$version.exe" "release-archive/"
          Copy-Item "LICENSE" "release-archive/LICENSE.txt"
          Copy-Item "README.md" "release-archive/Readme.txt"

          # Create zip
          Compress-Archive -Path "release-archive/*" -DestinationPath "release/$zipName"

          # Cleanup
          Remove-Item -Recurse -Force "release-archive"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            release/unitypackage-scanner-*.exe
            release/unitypackage-scanner-*.zip
            release/*.blockmap
          body: |
            ## ゆにぱけスキャナー ${{ github.ref_name }}

            **Windows専用リリース**

            このバージョンはWindows 10以降（64bit）専用です。
            macOS・Linux版は将来のバージョン（v1.0.0以降）で対応予定です。

            ### インストール方法

            **インストーラー版（推奨）**
            1. `unitypackage-scanner-0.9.0.exe` をダウンロード
            2. ダウンロードしたファイルを実行してインストール

            **ポータブル版（Zip）**
            1. `unitypackage-scanner-0.9.0-windows.zip` をダウンロード
            2. 解凍して任意のフォルダに配置
            3. `unitypackage-scanner-0.9.0.exe` を実行

            ### 主な変更点
            自動生成されたリリースノートを参照してください。
          generate_release_notes: true
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}